### PR TITLE
Testsuite: Fix patterns on stdarg-based tests

### PR DESCRIPTION
**Pull request by fxcoudert**
```
gcc/testsuite/ChangeLog:

	* gcc.dg/tree-ssa/stdarg-2.c: Adjust pattern.
	* gcc.dg/tree-ssa/stdarg-4.c: Adjust pattern.
	* gcc.dg/tree-ssa/stdarg-5.c: Adjust pattern.
```

### CODE REVIEW

**Comment by fxcoudert** [comment]
Adjust the patterns for darwin, which has a different type of `va_list` than AAPCS. The only think I'm not 100% sure is the patterns for `f1` and `f2` in `stdarg-5.c`: `f1: va_list escapes 1`. The other archs all have `escapes 0`, so this should be double-checked @iains before merging.

**Comment by iains** [comment]
TBH I am not sure what that actually means; so what I'd suggest is to revert that part of the patch - and apply the rest (unless you have time to research what that fail actually means).

**Comment by fxcoudert** [comment]
Let me look into it, and I'll report here.

**Comment by fxcoudert** [comment]
I have adjusted the PR to `f1: va_list escapes 0` and `f2: va_list escapes 0`. This means that part of the test will fail, but I am not fully convinced that the current result (`va_list escapes` being true) is right. The code dealing with this is in `gcc/tree-stdarg.c`, functions `optimize_va_list_gpr_fpr_size()` and `check_va_list_escapes()`.

I suggest we merge as is, fixing the rest of the testcases, and at some point we'll dig deeper into the specifics.

**Comment by fxcoudert** [comment]
(In particular, on x86_64 we get the `va_list` in `f1` and `f2` is not marked as escaping, I wonder where the different is coming from…)

**Comment by iains** [comment]
Yeah, let's leave that as pending and fix the stuff that makes sense

**Pull request merged**
