### PR TITLE
Fix configure script for Darwin 21

### PR DESCRIPTION
**Pull request by saagarjha**
This lets the build work on macOS Monterey.

### CODE REVIEW

**Comment by iains** [comment]
thanks for the patch - merged in for now.

I suspect that we will need changes in several places to handle darwin21 (it wasn't 100% clear if that was going to correspond to a major version jump again).  This is merged for now - but probably there will be a more general change to handle this for x86 as well as arm64.

**Comment by saagarjha** [comment]
Yeah, I'm pretty sure there's a couple places that parse `-mmacosx-version-min` and such that need patching. I'm going through those slowly and I'll put up a new patch for those soon.

**Comment by iains** [comment]
leave it with me for a few days, now you have noted that darwin21 is a new major version, I should be able to produce a patch in the next rebase for you to test.  I'd rather not produce duplicated  code for each macOS version, we should instead use some computed value.

Also, we should only need to set a minimum ld64 version for cross-compile cases where the version cannot be discovered from the configure process.

**Comment by saagarjha** [comment]
Sure thing. Here's what I have for now, anyways, I'll let you do the rest:

```diff
diff --git a/gcc/config/darwin-c.c b/gcc/config/darwin-c.c
index b0424a981e8..8b3dec25476 100644
--- a/gcc/config/darwin-c.c
+++ b/gcc/config/darwin-c.c
@@ -691,7 +691,7 @@ macosx_version_as_macro (void)
   if (!version_array)
     goto fail;
 
-  if (version_array[MAJOR] < 10 || version_array[MAJOR] > 11)
+  if (version_array[MAJOR] < 10 || version_array[MAJOR] > 12)
     goto fail;
 
   if (version_array[MAJOR] == 10 && version_array[MINOR] < 10)
diff --git a/gcc/config/darwin-driver.c b/gcc/config/darwin-driver.c
index 2c65870c615..e5574a44586 100644
--- a/gcc/config/darwin-driver.c
+++ b/gcc/config/darwin-driver.c
@@ -64,17 +64,17 @@ validate_macosx_version_min (const char *version_str)
 
   major = strtoul (version_str, &end, 10);
 
-  if (major < 10 || major > 11 ) /* MacOS 10 and 11 are known. */
+  if (major < 10 || major > 12 ) /* macOS 10, 11, and 12 are known. */
     return NULL;
 
   /* Skip a separating period, if there's one.  */
   version_str = end + ((*end == '.') ? 1 : 0);
 
-  if (major == 11 && *end != '\0' && !ISDIGIT (version_str[0]))
-     /* For MacOS 11, we allow just the major number, but if the minor is
+  if (major > 10 && *end != '\0' && !ISDIGIT (version_str[0]))
+     /* For macOS 11+, we allow just the major number, but if the minor is
 	there it must be numeric.  */
     return NULL;
-  else if (major == 11 && *end == '\0')
+  else if (major > 10 && *end == '\0')
     /* We will rewrite 11 =>  11.0.0.  */
     need_rewrite = true;
   else if (major == 10 && (*end == '\0' || !ISDIGIT (version_str[0])))
@@ -172,7 +172,7 @@ darwin_find_version_from_kernel (void)
       if (minor_vers > 0)
 	minor_vers -= 1; /* Kernel 20.3 => macOS 11.2.  */
       /* It's not yet clear whether patch level will be considered.  */
-      asprintf (&new_flag, "11.%02d.00", minor_vers);
+      asprintf (&new_flag, "%d.%02d.00", major_vers - 9, minor_vers);
     }
   else if (major_vers - 4 <= 4)
     /* On 10.4 and earlier, the old linker is used which does not
```

**Comment by iains** [comment]
actually, it looks like you have most of the changes there - have you tested this with x86_64, or only with Arm64?

Note that ISTR someone from Apple mentioning that it might be necessary to map minor versions with some  lookup table (there might not be 1:1 correspondence). 

What is the current minor version ? (as you can tell I don't currently have access to darwin21).

**Comment by saagarjha** [comment]
Just arm64 for now–GCC is part of a larger thing I need to build and I was trying to unblock that. I'll try this patch on an Intel machine and get back to you. Regarding versions, as far as I can tell you're talking about matching up what `uname -r` gives with the marketing version number? This is what they currently are on the first beta:

```console
$ sw_vers -productVersion
12.0
$ uname -r
21.0.0
```

But this way lies madness IMO. The marketing version changes based on, well, marketing: it doesn't match the Darwin version number at all. I believe the build number's letter does, but I'm not sure if that is worth parsing out.

**Comment by iains** [comment]
yeah, but historically we have allowed a configuration to pick up the version information from the kernel.  So that the -mmacosx-version-min is found that way (meaning that the user doesn't need to apply it).  For 10.x (most of the time) there was correspondence.  For 11 minor seemed to be kernel-minor-1.

pre-release numbering needn't be too picky, I guess.

I am testing a rebase with a few changes (one of which is a combined patch for D21) - hopefully tomorrow or Saturday I should be able to push it.

**Comment by saagarjha** [comment]
Ok, so I tested the patch on x86_64 and it seems to have built there too. Using kernel minor-1 is probably a good guess but it's bound to diverge from the actual number at some point, but it might not matter enough to be worth caring about. Let me know if you have new changes and I'd be happy to test them out :)

**Comment by iains** [comment]
I've pushed a rebase onto recent master; your patches are included - so it ought to work on Darwin21 - let me know if there are any glitches (there's at least one more place to make changes - for the sanitiser - but that's not expected to work yet).

**Comment by saagarjha** [comment]
I was able to compile and run a simple test program, so it seems to be working! The only trouble that I ran into was that it would embed a `@rpath/libgcc_s.1.1.dylib` into the binary, but I had my GCC installed at a prefix so the library wasn't found (I got around it with `DYLD_LIBRARY_PATH`). But this might just be me misconfiguring it.

**Comment by iains** [comment]
> The only trouble that I ran into was that it would embed a `@rpath/libgcc_s.1.1.dylib` into the binary, but I had my GCC installed at a prefix so the library wasn't found 

This is intended (it is a solution to a long-standing issue with GCC builds and systems with SIP) - it should 'just work'.

The target libraries are built with @rpath/libxxxxx.dylib - and the compiler should insert rpaths for its installation into any built exe.  Additionally, if you install the target libraries into a fixed address, an existing exe that has hard-wired paths to find them there should still succeed.

So, for example, if I have it installed at ```/Users/iains/aarch64-apple-darwin20/gcc-12-0-0```

configured like this:

```
Users/iains/src-local/gcc-master/configure --prefix=/Users/iains/aarch64-apple-darwin20/gcc-12-0-0 --build=aarch64-apple-darwin20 --with-sysroot=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk --disable-libstdcxx-pch --enable-languages=all CC=aarch64-apple-darwin20-gcc CXX=aarch64-apple-darwin20-g++
```

then the built exes contain:

```
Load command 16
          cmd LC_RPATH
      cmdsize 104
         path /Users/iains/aarch64-apple-darwin20/gcc-12-0-0/lib/gcc/aarch64-apple-darwin20/12.0.0 (offset 12)
Load command 17
          cmd LC_RPATH
      cmdsize 112
         path /Users/iains/aarch64-apple-darwin20/gcc-12-0-0/lib/gcc/aarch64-apple-darwin20/12.0.0/../../.. (offset 12)
```
which are ```rpath``` settings which are correct for the libraries and for an exec called "t"...

```
DYLD_PRINT_LIBRARIES=1 ./t
dyld: loaded: <66195C74-9CED-3F20-9B2F-A14DE14D24F3> /Users/iains/scratch/./t
dyld: loaded: <0A7386FA-099A-3318-84C2-35F902E1BF1D> /Users/iains/aarch64-apple-darwin20/gcc-12-0-0/lib/libgcc_s.1.1.dylib
dyld: loaded: <A03485B7-4C44-3F47-8BF9-5D6E1BE0CF27> /usr/lib/libSystem.B.dylib
... etc etc.
```

IFF you are adding your own rpaths to an exe - then you will also need to add the GCC ones (unless you are packaging the GCC runtimes local to, for example, a delivered app).  This is because user-provided rpaths override the ones automatically added by the compiler (necessary in order to build packages in this way).

**Comment by saagarjha** [comment]
This is actually what I expected to happen, actually, but the binary that was generated is missing the `LC_RPATH` command…

**Comment by iains** [comment]
I see; let's make sure we don't have bug then.

1) Is your configure command different in any significant way from mine?

2) suppose you build a "helloworld.c" with "-v" and examine the link line, mine looks like this:
```
/usr/bin/ld -syslibroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/ -dynamic -arch arm64 -macosx_version_min 11.3.0 -weak_reference_mismatches non-weak -o t -L/Users/iains/aarch64-apple-darwin20/gcc-12-0-0/lib/gcc/aarch64-apple-darwin20/12.0.0 -L/Users/iains/aarch64-apple-darwin20/gcc-12-0-0/lib/gcc/aarch64-apple-darwin20/12.0.0/../../.. /var/folders/1t/4hb9yprd4_gfxnjzntr1psgw0000fw/T//ccRTZBcL.o -lgcc_s.1.1 -lgcc -lSystem -lgcc -no_compact_unwind -rpath @loader_path -rpath /Users/iains/aarch64-apple-darwin20/gcc-12-0-0/lib/gcc/aarch64-apple-darwin20/12.0.0 -rpath /Users/iains/aarch64-apple-darwin20/gcc-12-0-0/lib/gcc/aarch64-apple-darwin20/12.0.0/../../.. -v
```
the rpaths are supplied as expected .

On gcc304 I don't have control over the installation of the command-line-tools - the version of ld installed is  

```
$ ld -v
@(#)PROGRAM:ld  PROJECT:ld64-650.9
```

**Comment by saagarjha** [comment]
1. Here's my full configure command: 
```console
$ ./configure --with-gmp=/tmp/macports --with-mpfr=/tmp/macports --with-mpc=/tmp/macports --with-native-system-header-dir=/usr/include --build=aarch64-apple-darwin21.0.0 --disable-multilib --with-sysroot=/Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk --prefix=/tmp/gcc
```
2. Here's the call to ld:
```
/usr/bin/ld -syslibroot /Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/ -dynamic -arch arm64 -macosx_version_min 12.0.0 -weak_reference_mismatches non-weak -o a.out -L/private/tmp/gcc/bin/../lib/gcc/aarch64-apple-darwin21.0.0/12.0.0 -L/private/tmp/gcc/bin/../lib/gcc -L/private/tmp/gcc/bin/../lib/gcc/aarch64-apple-darwin21.0.0/12.0.0/../../.. /var/folders/06/g6hwj5mj7tvdl36wcdp83n7w0000gn/T//ccrMqVeD.o -lgcc_s.1.1 -lgcc -lSystem -lgcc -no_compact_unwind -v
```
It seems to be missing the rpath part…I'm just using the Xcode ld but I don't think it's the problem here. But, for reference:
```console
$ ld -v
@(#)PROGRAM:ld  PROJECT:ld64-705
```

**Comment by iains** [comment]
OK, I agree the ld version is irrelevant, since the rpaths are not being supplied.

please could you try the configure without ```--disable-multilib``` (that seems the most likely to interact).

As a matter of interest what is the intention of using ```--with-native-system-header-dir=/usr/include``` ?

My useful rule-of-thumb is to keep configure lines as simple as possible - only adding things for known good reasons.

**Comment by iains** [comment]
AH!!!! , an alternate explanation could be that we have still got version change fixes to do ...
.. untested (no Darwin21 system yet), please see if it fixes this four you.

```
diff --git a/gcc/configure b/gcc/configure
index 07c0a5be263..ea529a22433 100755
--- a/gcc/configure
+++ b/gcc/configure
@@ -30513,7 +30513,7 @@ if test "x$enable_darwin_at_rpath" = "xyes"; then
   #
   case "$target" in
     # It is valid for targets from Darwin9.
-    *-darwin20* | *-darwin1[0-9]* | *-darwin9*)
+    *-darwin2[0-9]* | *-darwin1[0-9]* | *-darwin9*)
       tm_defines="$tm_defines USE_DEFAULT_RPATH "
       ;;
   esac
diff --git a/gcc/configure.ac b/gcc/configure.ac
index dc7952dcc61..0af5b0acbbf 100644
--- a/gcc/configure.ac
+++ b/gcc/configure.ac
@@ -6267,7 +6267,7 @@ if test "x$enable_darwin_at_rpath" = "xyes"; then
   # 
   case "$target" in
     # It is valid for targets from Darwin9.
-    *-darwin20* | *-darwin1[[0-9]]* | *-darwin9*)
+    *-darwin2[[0-9]]* | *-darwin1[[0-9]]* | *-darwin9*)
       tm_defines="$tm_defines USE_DEFAULT_RPATH "
       ;;
   esac
```

**Comment by iains** [comment]
it looks to me that this is not complete - and the larger patch for lib tool needs to be modified - will try and do that later and push a revised patch.

**Comment by iains** [comment]
TBH I don't normally push patches I can't test - but I did check that the build runs OK on Darwin19 and Darwin20.

I've now pushed a revised branch that I *think* catches all the places we needed a change for Darwin21 (except for the sanitiser which is on the TODO).  Please let me know if this now behaves properly for you (or if there's any incremental patch you want to propose).

**Comment by saagarjha** [comment]
I just tried it and it seemed to work for me :)

**Pull request merged**
